[package]
name = "mini_robot"
version = "0.1.0"
edition = "2021"

[dependencies]
hostname = "0.3.1"
pnet = "0.34.0"
log = "0.4"
env_logger = "0.10"
colored = "2.0"
dotenv = "0.15"
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
sysinfo = "0.30.12"