name: miniRobot CI

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust: [stable]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true

    - name: Build project
      run: cargo build --verbose --all-targets

    - name: Run tests
      run: cargo test --verbose -- --nocapture

    - name: Create bin directory
      run: mkdir -p upload_bin/{linux,macos,windows}

    - name: Publish binary
      if: success()
      run: |
        if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
          ls -la target/debug/*
          cp target/debug/mini_robot{,_info,_test} upload_bin/linux/
          ls -la upload_bin/linux/*
        elif [ "${{ matrix.os }}" = "macos-latest" ]; then
          ls -la target/debug/*
          cp target/debug/mini_robot{,_info,_test} upload_bin/macos/
          ls -la upload_bin/macos/*
        elif [ "${{ matrix.os }}" = "windows-latest" ]; then
          ls -la target/debug/*
          cp target/debug/mini_robot{,_info,_test}.exe upload_bin/windows/
          ls -la upload_bin/windows/*
        fi

    - name: Upload binary
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: binaries-${{ matrix.os }}
        path: upload_bin/

  create_tag:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Extract version from Cargo.toml
      id: get_version
      run: |
        VERSION=$(grep '^version' Cargo.toml | sed 's/version = "//' | sed 's/"//')
        echo "$VERSION" > version.txt

    - name: Create tag
      id: create_tag
      run: |
        VERSION=$(cat version.txt)
        git tag $VERSION
        git push --tags --force
      env:
        GITHUB_TOKEN: ${{ secrets.REPOS_WORKFLOW_TOKEN }}

    - name: Upload version file
      uses: actions/upload-artifact@v2
      with:
        name: version
        path: version.txt

  release:
    needs: create_tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download Linux binaries
      uses: actions/download-artifact@v2
      with:
        name: binaries-ubuntu-latest
        path: ./upload_bin/linux

    - name: Download macOS binaries
      uses: actions/download-artifact@v2
      with:
        name: binaries-macos-latest
        path: ./upload_bin/macos

    - name: Download version file
      uses: actions/download-artifact@v2
      with:
        name: version
        path: ./

    - name: Read version
      id: read_version
      run: |
        VERSION=$(cat version.txt)
        echo "VERSION=$VERSION" >> $GITHUB_ENV

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.REPOS_WORKFLOW_TOKEN }}
      with:
        tag_name: ${{ env.VERSION }}
        release_name: Release ${{ env.VERSION }}
        draft: false
        prerelease: false

    - name: Upload Linux Release Assets
      if: steps.create_release.outputs.upload_url
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.REPOS_WORKFLOW_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./upload_bin/linux/*
        asset_name: minirobot_linux_binaries.zip
        asset_content_type: application/zip

    - name: Upload macOS Release Assets
      if: steps.create_release.outputs.upload_url
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.REPOS_WORKFLOW_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./upload_bin/macos/*
        asset_name: minirobot_macos_binaries.zip
        asset_content_type: application/zip
