name: Rust CI

on:
  push:
    branches:
      - master
  release:
    types: [created, published]

jobs:
  build:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, macos-latest]
        rust: [stable]

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Rust
      uses: actions-rs/toolchain@v1
      with:
        toolchain: ${{ matrix.rust }}
        override: true

    - name: Build project
      run: cargo build --verbose --all-targets

    - name: Run tests
      run: cargo test --verbose -- --nocapture

    - name: Create bin directory
      run: mkdir -p upload_bin

    - name: Publish binary
      if: success()
      run: |
        if [ "${{ matrix.os }}" = "ubuntu-latest" ]; then
          cp target/debug/mini_robot{,_info,_test} upload_bin/
        elif [ "${{ matrix.os }}" = "macos-latest" ]; then
          cp target/debug/mini_robot{,_info,_test} upload_bin/
        elif [ "${{ matrix.os }}" = "windows-latest" ]; then
          cp target/debug/mini_robot{,_info,_test}.exe upload_bin/
        fi

    - name: Upload binary
      if: success()
      uses: actions/upload-artifact@v2
      with:
        name: binaries-${{ matrix.os }}
        path: upload_bin/

  create_tag:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Extract version from Cargo.toml
      id: get_version
      run: |
        VERSION=$(grep '^version' Cargo.toml | sed 's/version = "//' | sed 's/"//')
        echo "VERSION=$VERSION" >> $GITHUB_ENV
        echo "::set-output name=VERSION::$VERSION"

    - name: Create tag
      id: create_tag
      run: |
        git tag ${{ steps.get_version.outputs.VERSION }}
        git push origin ${{ steps.get_version.outputs.VERSION }}
      env:
        GITHUB_TOKEN: ${{ secrets.REPOS_WORKFLOW_TOKEN }}

  release:
    needs: create_tag
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Download Linux binaries
      uses: actions/download-artifact@v2
      with:
        name: binaries-ubuntu-latest
        path: ./bin/linux

    - name: Download macOS binaries
      uses: actions/download-artifact@v2
      with:
        name: binaries-macos-latest
        path: ./bin/macos

    - name: Create GitHub Release
      id: create_release
      uses: actions/create-release@v1
      env:
        GITHUB_TOKEN: ${{ secrets.REPOS_WORKFLOW_TOKEN }}
      with:
        tag_name: ${{ steps.get_version.outputs.VERSION }}
        release_name: Release ${{ steps.get_version.outputs.VERSION }}
        draft: false
        prerelease: false

    - name: Upload Linux Release Assets
      if: steps.create_release.outputs.upload_url
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.REPOS_WORKFLOW_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bin/linux/*
        asset_name: minirobot_linux_binaries.zip
        asset_content_type: application/zip

    - name: Upload macOS Release Assets
      if: steps.create_release.outputs.upload_url
      uses: actions/upload-release-asset@v1
      env:
        GITHUB_TOKEN: ${{ secrets.REPOS_WORKFLOW_TOKEN }}
      with:
        upload_url: ${{ steps.create_release.outputs.upload_url }}
        asset_path: ./bin/macos/*
        asset_name: minirobot_macos_binaries.zip
        asset_content_type: application/zip
